# Generated by Django 5.1 on 2024-08-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='creation_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
