# Generated by Django 5.1 on 2024-09-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0005_booking_status_room_is_available_room_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_available',
        ),
    ]
